#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Abraham Joseph Okayli Masaryk
# Build "GeoDynamix Beta.app" — a Dock-launchable bundle wrapping the shell.
#
#   conda activate geodynamix          # the env GeoDynamix is installed in
#   scripts/make_app.sh                # writes ~/Applications/GeoDynamix Beta.app
#   scripts/make_app.sh /some/dir      # writes /some/dir/GeoDynamix Beta.app
#
# The launcher runs THIS checkout with the Python of the env that was active when it was built
# (override with PYTHON=/path/to/python). The bundle is generated OUTSIDE the repo with this
# machine's paths baked in at build time (no absolute machine paths may live IN the repo; a
# per-machine launcher is the legitimate home for them). Re-run after moving the checkout or
# the env. Its own name and bundle id, so it never replaces a DynamiX.app beside it.
set -e
cd "$(dirname "$0")/.."
REPO="$(pwd)"

PY="${PYTHON:-$(command -v python || command -v python3)}"
"$PY" -c "import PySide6" 2>/dev/null || {
  echo "make_app.sh: $PY cannot import PySide6 -- activate the env GeoDynamix is installed in" >&2
  exit 1
}

DEST="${1:-$HOME/Applications}"
APP="$DEST/GeoDynamix Beta.app"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# --- icon: paint once at 1024, downscale into an iconset, compile to icns ---
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
QT_QPA_PLATFORM=offscreen "$PY" scripts/make_icon.py "$TMP/icon_1024.png"
ICONSET="$TMP/GeoDynamix.iconset"
mkdir -p "$ICONSET"
for s in 16 32 128 256 512; do
  sips -z "$s" "$s" "$TMP/icon_1024.png" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
  d=$((s * 2))
  sips -z "$d" "$d" "$TMP/icon_1024.png" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/GeoDynamix.icns"

# --- launcher: paths resolved NOW, for THIS machine ---
cat > "$APP/Contents/MacOS/GeoDynamix" <<EOF
#!/bin/bash
# Generated by scripts/make_app.sh — re-run it if the checkout or env moves.
export PYTHONPATH="$REPO/src"
exec "$PY" -m dynamix.shell.app "\$@"
EOF
chmod +x "$APP/Contents/MacOS/GeoDynamix"

cat > "$APP/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>            <string>GeoDynamix Beta</string>
  <key>CFBundleDisplayName</key>     <string>GeoDynamix Beta</string>
  <key>CFBundleExecutable</key>      <string>GeoDynamix</string>
  <key>CFBundleIconFile</key>        <string>GeoDynamix</string>
  <key>CFBundleIdentifier</key>      <string>edu.uh.geodynamix-beta</string>
  <key>CFBundlePackageType</key>     <string>APPL</string>
  <key>CFBundleShortVersionString</key> <string>0.1.0</string>
  <key>CFBundleVersion</key>         <string>0.1.0</string>
  <key>LSMinimumSystemVersion</key>  <string>11.0</string>
  <key>NSHighResolutionCapable</key> <true/>
  <key>LSApplicationCategoryType</key> <string>public.app-category.education</string>
</dict>
</plist>
EOF

touch "$APP"   # nudge Finder/Dock to refresh the icon
echo "built $APP"
